### ISSUE TITLE
Idempotency keys: using a completer might be unexpected to the client

### ISSUE THREAD

**Issue by juona** [brandur/sorg#268]
Hi @brandur,

Many thanks for your article on idempotence, I used it to build idempotent orders and payments in my own system. 

However, I ran into a problem that I am not able to wrap my head around. I would really appreciate if you could provide your take on the issue!

In the article you wrote:

> Usually clients are willing to [push indeterminate requests to completion] because they want to see their requests go through, but there can be cases where a client starts working, never quite finishes, and drops forever.

So here's an example situation, if I understood you correctly:

1. Server creates an order in the DB with status `PAYMENT_PENDING`.
2. Server calls Stripe to execute the payment and it resolves successfully.
3. Server fails to update the order to status `PAID` because there's some problem with the DB or something of the sort.

I update the idempotence record after each step so the whole thing is safe to retry, but the user decides not to.

At this point I have a situation where the user _has paid_ but the order is not placed, and they are not even aware that they actually paid (unless they check their bank statement, that is).

This is where I get confused. If I tell the user that there was an error, most people (_[citation needed]_) would rightfully expect that they were not charged and would deem it safe to abandon the operation. Furthermore, a lot of people (_[citation needed]_) would consider an abandoned operation to be equivalent to a cancelled one. So a completer pushing such orders to completion would be unexpected.

**Have I misunderstood something? Are you aware of any alternative approaches?**

- Perhaps, if I have faith in the completer, I should let the user know that "order is processing" and will be updated later, instead of showing an error?
- Alternatively, my completer could attempt to _revert_ any ambiguous operations. However, since I failed to save any reference to the payment, it might now always be feasible (e. g. Stripe does not seem to provide a practical way to lookup payments using metadata).

What's your take?

**Comment by brandur** [comment]
@juona Thanks for reading!

>  Furthermore, a lot of people ([citation needed]) would consider an abandoned operation to be equivalent to a cancelled one. So a completer pushing such orders to completion would be unexpected.

So this is definitely a tricky edge case, but one thing to think about is that from _Stripe's perspective_ (i.e. how the API is implemented), the payment which seems to have failed probably does have a definitive state.

By extension, a pusher that you build on your end that tries to converge these types of failures isn't actually manipulating the result of the payment — the payment is already done (or not done), and all the pusher is doing is using an idempotency key to make sure that you get a result back to store on your end.

Once you have that result, you can decide what to do with it. I could imagine either (1) completing the transaction, but making sure to tell the user about it via some side channel like email to make sure they know about it, or (2) refunding. There's probably other answers too.

> Perhaps, if I have faith in the completer, I should let the user know that "order is processing" and will be updated later, instead of showing an error?

IMO, you should definitely show a "payment completed" page where possible, but if the result really is ambiguous, it's certainly not a bad idea to signal that to the user (and maybe tell them to check their email, contact support, or something).

You could also try something where the client will wait for the server to retry a few times on such a failure just to maximize the chances that you get a definitive result back.

> Alternatively, my completer could attempt to revert any ambiguous operations. However, since I failed to save any reference to the payment, it might now always be feasible (e. g. Stripe does not seem to provide a practical way to lookup payments using metadata).

See above, but that's why you want a process to push indeterminate Stripe operations through. The idempotency key is your lookup key — you just need to make sure to get a result back with it (which will include all the other IDs you need).

**Comment by juona** [comment]
Usually answers that I receive on the Internet leave room for follow-up questions, but this is not the case : ]

Thank you so much for the time you took to read my question and respond to it - very prompt too! Have a great 2021 (no jokes)!

**Comment by brandur** [comment]
Haha, glad some of it was useful. No problem and best wishes for 2021 for you as well!
