### ISSUE TITLE
Why not use check constraints?

### ISSUE THREAD

**Issue by mzealey** [brandur/sorg#276]
In sorg/content/articles/text.md you talk about why you now use varchar rather than text. But changing lengths of varchar (eg shortening) will still cause issues. Why not just use text field but with a check constraint for ensuring the current lengths on input as these can be changed at any point in time with no issue...

**Comment by brandur** [comment]
I've previously recommended `CHECK` constraints (see [here for example](https://brandur.org/idempotency-keys)), but the gap's significantly closed over time in that `VARCHAR` gets many of the same benefits. As noted in the article, loosening a `VARCHAR` constraint is a free operation just like it is for `CHECK`. Like a `VARCHAR`, `CHECK` must also be checked when a constraint is tightened.

`VARCHAR` makes for cleaner code samples, so I'd generally prefer its use in an article like this one.

There were some other arguments made in favor of `CHECK` in the comments, like that changing a `VARCHAR` has major ramifications for derivative views. I'd have to look into this one a bit more and make sure that it's actually a thing — these claims are made with no backing code or references so they need to be checked.

I'll probably do a longer writeup of `CHECKED` versus `VARCHAR` at some point because it seems to be an area that a lot of people have questions about.
